name: Python CI

on:
  push:
    branches: [ master ] # Changed from main - USER: PLEASE VERIFY YOUR DEFAULT BRANCH
  pull_request:
    branches: [ master ] # Changed from main - USER: PLEASE VERIFY YOUR DEFAULT BRANCH

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pipx install poetry
        poetry --version

    - name: Configure Poetry for in-project virtualenv
      run: |
        poetry config virtualenvs.in-project true --local

    - name: Cache Poetry virtualenv
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ matrix.python-version }}-

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi

    - name: Run tests
      run: |
        poetry run python -m unittest discover tests
